### PR TITLE
Prevent builds on Windows 64-bit Node.js

### PR DESCRIPTION
**Pull request by robertsmieja**

### CODE REVIEW

**Comment by denoflionsx** [comment]
Why in the world would I merge this? It would prevent me from building my own project.

**Comment by robertsmieja** [comment]
I'm able to run this on my 64-bit machine, and I tested this using 32-bit and 64-bit Node.js.

The value of `process.arch` is "x32" when using Node.js 12.18.4 32-bit, and Node.js 12.18.4 64-bit.

**Comment by robertsmieja** [comment]
@denoflionsx do you mind letting me know if you had time to take a look at the information I posted above?

Thanks for taking a look a this.

**Comment by denoflionsx** [comment]
Preventing building on 64bit is entirely unnecessary after 16f5a5c9e1da1066eeaa425794d57c6ebda94261.

**Pull request closed without merging**
